# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('profile_pic', models.CharField(blank=True, max_length=200)),
                ('fb_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('fcm_token', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
    ]
