# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporterprofile',
            name='fb_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='reporterprofile',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reporterprofile',
            name='profile_pic',
            field=models.CharField(max_length=200),
        ),
    ]
