# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=utils.scramble_uploaded_filename)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=250)),
                ('why', models.TextField()),
                ('when', models.CharField(default='', max_length=20)),
                ('where', models.CharField(default='Unkown', max_length=200)),
                ('who', models.TextField()),
                ('author', models.CharField(default='Anonymous', max_length=250)),
                ('fb_id', models.CharField(max_length=250)),
                ('local_media_paths', models.CharField(default='', max_length=5000)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='media',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='stories.Story'),
        ),
    ]
