# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='when',
            field=models.CharField(default='', max_length=20),
        ),
    ]
