# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='why',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='story',
            name='fb_id',
        ),
        migrations.AddField(
            model_name='story',
            name='assignmentId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='local_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='uid',
            field=models.CharField(default='unknown', max_length=250),
        ),
        migrations.AddField(
            model_name='story',
            name='updated',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='story',
            name='uploaded',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='local_media_paths',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
