# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporterprofile',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
