# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170801_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporterprofile',
            name='fcm_token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
