# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20170801_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporterprofile',
            name='fcm_token',
            field=models.CharField(default=' ', max_length=100, null=True),
        ),
    ]
