# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20170801_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporterprofile',
            old_name='fb_id',
            new_name='uid',
        ),
        migrations.AddField(
            model_name='reporterprofile',
            name='location',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reporterprofile',
            name='fcm_token',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
