# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=500)),
                ('required_media', models.CharField(choices=[(b'Image', b'image'), (b'Audio', b'audio'), (b'Video', b'video'), (b'image + video', b'image & video'), (b'image + audio', b'image & audio'), (b'audio + video', b'audio & video'), (b'image + audio + video', b'image & audio & video')], default=b'Image', max_length=5)),
                ('featured_image', models.ImageField(blank=True, upload_to=utils.scramble_uploaded_filename)),
                ('number_of_responses', models.IntegerField(default=None, null=True)),
                ('deadline', models.DateField()),
                ('author', models.CharField(default=b'Anonymous', max_length=100)),
                ('assignment_location', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
